title: Javae Elliott
description: My portfolio and data science projects
baseurl: "" 
url: "https://javaelliott1.github.io"

<<<<<<< HEAD
=======
# Minimal Mistakes theme
>>>>>>> 03d300b2261158bb97d02ad4942fe51976de0f2b
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
# Navigation
nav:
  - title: About
    url: /about/
  - title: Experience
    url: /experience/
  - title: Projects
    url: /projects/
  - title: Skills
    url: /skills/
  - title: Contact
    url: /contact/
