title: Javae Elliott
description: My awesome site
baseurl: "" # leave empty for user sites
url: "https://javaelliott1.github.io"

# Minimal Mistakes theme
remote_theme: mmistakes/minimal-mistakes@4.28.0
plugins:
  - jekyll-feed

# Navigation
nav:
  - title: About
    url: /about/
  - title: Experience
    url: /experience/
  - title: Projects
    url: /projects/
  - title: Skills
    url: /skills/
  - title: Contact
    url: /contact/